# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Things"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Minhyuk Kim"
description              : "Mininny's mini blog."
url                      : "https://www.mininny.dev"
# baseurl                  : ""
repository               : mininny/mininny.github.io
# teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
# masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google" # , "google-universal", "custom"
  google:
    tracking_id          : UA-161734775-1
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Mininny"
  avatar           : "/assets/images/bio-photo.png"
  bio              : " lover"
  location         : "Seoul"
  email            : mininny1004@gmail.com
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.mininny.dev"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/mininnykim/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mininny"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://www.github.com/mininny
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:mininny1004@email.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.mininny.dev"
    - label: "Linkedin"
      icon: "fab fa-linkedin-in"
      url: "https://www.linkedin.com/in/mininnykim/"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: jekyll-archives
  path: /
tag_archive:
  type: jekyll-archives
  path: /
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /:name/
    tag: /:name/

category_list: [ ios, knowledge_base, translation ]

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  app_stuff:
    output: true
    permalink: /:collection/:path/
  temp_guide:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
    # _iOS
  - scope:
      path: "_ios"
      type: ios
    values:
      layout: single
      read_time: true
      author_profile: true
      share: true
      comments: true
  # _app_stuff
  - scope:
      path: "_app_stuff"
      type: app_stuff
    values:
      layout: single
      read_time: true
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "app_stuff"
  # _knowledge_base
  - scope:
      path: "_knowledge_base"
      type: knowledge_base
    values:
      layout: single
      read_time: true
      author_profile: true
      share: true
      comments: true
      sidebar:
        nav: "knowledge_base"
  # _translation
  - scope:
      path: "_translation"
      type: translation
    values:
      layout: single
      read_time: true
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "translation"
  # about_me
  - scope:
      path: ""
      type: about_me
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "about_me"
  # _temp_guide
  - scope:
      path: "_temp_guide"
      type: temp_guide
    values:
      layout: single
      read_time: true
      author_profile: false
      share: false
      comments: false